import streamlit as st
import pandas as pd
import numpy as np
import json
import plotly.express as px
import matplotlib.pyplot as plt

# --- 1. DATA LOADING FUNCTION ---

def load_metrics(filename='results_data.json'):
    """Loads metrics from the JSON file generated by main.py."""
    try:
        with open(filename, 'r') as f:
            data = json.load(f)
        # Support both old format (metrics at top-level) and new format with 'metrics' key
        if isinstance(data, dict) and 'metrics' in data:
            data = data['metrics']
        
        # Convert list data back into a format suitable for plotting (e.g., Series)
        processed_data = {}
        for algo, metrics in data.items():
            processed_data[algo] = {
                'time': pd.Series(metrics['time']),
                'cost': pd.Series(metrics['cost']),
                'util': pd.Series(metrics['util']),
                'resp': pd.Series(metrics['resp'])
            }
        return processed_data
    except FileNotFoundError:
        st.error(f"Error: The results file '{filename}' was not found. Please run main.py first to generate the data.")
        return None
    except Exception as e:
        st.error(f"Error loading metrics: {e}")
        return None

# --- 2. PLOTTING FUNCTIONS ---

def create_line_chart(metrics_df, y_col, title, y_label):
    """Creates a Plotly line chart for comparison."""
    # Melt the DataFrame for Plotly, using the Task index as the x-axis
    melted_df = metrics_df.reset_index().melt(
        id_vars='index',
        value_vars=metrics_df.columns,
        var_name='Algorithm',
        value_name=y_col
    )
    melted_df.rename(columns={'index': 'Task'}, inplace=True)
    
    fig = px.line(melted_df, x='Task', y=y_col, color='Algorithm', 
                  markers=True, title=title)
    fig.update_layout(yaxis_title=y_label)
    return fig

# --- 3. STREAMLIT APP LAYOUT ---

def app():
    st.set_page_config(layout="wide", page_title="N2TC+GATA Scheduler Evaluation")

    st.title("🧠Resource Allocation Performance Dashboard")
    st.markdown("---")

    metrics_data = load_metrics()
    if metrics_data is None:
        return

    # Try to load extra info (relative performance table) if present
    try:
        with open('results_data.json', 'r') as f:
            raw = json.load(f)
        extra = raw.get('extra', {}) if isinstance(raw, dict) else {}
        rel_table = extra.get('relative_performance_table') if isinstance(extra, dict) else None
        rel_scores = extra.get('relative_performance') if isinstance(extra, dict) else None
    except Exception:
        rel_table = None
        rel_scores = None

    # If available, show the relative performance ASCII table and a compact DataFrame
    if rel_table:
        st.subheader("Relative Performance Scores")
        st.code(rel_table)

    # Convert the dictionary of results into a single DataFrame for easier manipulation
    df_list = []
    for algo, data in metrics_data.items():
        df_temp = pd.DataFrame(data)
        df_temp['Algorithm'] = algo
        df_list.append(df_temp)

    # Calculate average metrics for the comparative table (Table III)
    summary_list = []
    for algo, data in metrics_data.items():
        # Ensure data is converted to Series/numpy arrays for mean calculation
        util_series = data.get('util')
        resp_series = data.get('resp')
        cost_series = data.get('cost')
        time_series = data.get('time')

        summary_list.append({
            'Algorithm': algo,
            'Utility (Avg)': float(np.mean(util_series)) if util_series is not None and len(util_series) > 0 else 0,
            'Response Time (Avg)': float(np.mean(resp_series)) if resp_series is not None and len(resp_series) > 0 else 0,
            'Cost (Avg)': float(np.mean(cost_series)) / 10 if cost_series is not None and len(cost_series) > 0 else 0,
            'Execution Time (Avg)': float(np.mean(time_series)) / 10 if time_series is not None and len(time_series) > 0 else 0,
        })
    
    summary_df = pd.DataFrame(summary_list)
    
    # --- SECTION: OVERVIEW AND TABLE III ---
    st.header("Overview and Evaluation Summary (Table III)")
    
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("**Hybrid Model (N2TC+GATA):**")
        st.info("The Proposed Approach uses a Neural Network (N2TC) for task classification and a Genetic Algorithm (GATA) for resource optimization to balance fairness, cost, and speed.")
    
    with col2:
        st.markdown("**Average Performance Metrics (Normalized)**")
        st.dataframe(
            summary_df.set_index('Algorithm').style.format('{:.3f}'),
            use_container_width=True
        )

    st.markdown("---")
    
    # --- SECTION: GRAPHICAL COMPARISON ---
    st.header("Graphical Comparison of 10 Tasks (Fig. 5, 6, 7, 8)")
    st.write("View the performance trajectory across the 10 selected tasks for all five scheduling methods.")

    
    # Use tabs for a clean interface
    tab1, tab2, tab3, tab4 = st.tabs(["Execution Time (Fig. 5)", "System Utility (Fig. 6)", "Total Cost (Fig. 7)", "Response Time (Fig. 8)"])

    # 1. Execution Time (Fig 5)
    with tab1:
        df_time = pd.DataFrame({algo: data['time'] for algo, data in metrics_data.items()})
        fig_time = create_line_chart(df_time, "Execution Time (s)", "Fig. 5: Execution Times of 10 Tasks (Cumulative)", "Time (s)")
        st.plotly_chart(fig_time, use_container_width=True)

    # 2. System Utility (Fig 6)
    with tab2:
        df_util = pd.DataFrame({algo: data['util'] for algo, data in metrics_data.items()})
        # Plotly is better with un-accumulated data here since Utility is a rate, not cumulative
        fig_util = create_line_chart(df_util, "Utility (%)", "Fig. 6: System Utilization Rate (Task-by-Task)", "Utility (%)")
        st.plotly_chart(fig_util, use_container_width=True)

    # 3. Total Cost (Fig 7)
    with tab3:
        df_cost = pd.DataFrame({algo: data['cost'] for algo, data in metrics_data.items()})
        fig_cost = create_line_chart(df_cost, "Cost ($)", "Fig. 7: Costs of Executing Tasks (Cumulative)", "Cost ($)")
        st.plotly_chart(fig_cost, use_container_width=True)

    # 4. Response Time (Fig 8)
    with tab4:
        df_resp = pd.DataFrame({algo: data['resp'] for algo, data in metrics_data.items()})
        fig_resp = create_line_chart(df_resp, "Response Time (s)", "Fig. 8: Response Times of 10 Tasks (Task-by-Task)", "Time (s)")
        st.plotly_chart(fig_resp, use_container_width=True)


if __name__ == "__main__":
    app()